services:
  lyos-bot:
    build: .
    restart: on-failure
    env_file: .env
    networks:
      - shared_net
    tty: true
    volumes:
      - ./logs:/app/logs

networks:
  shared_net:
    external: true
