services:
  lyos-bot:
    build: .
    restart: on-failure
    env_file: .env
    networks:
      - shared-db-net
    tty: true
    volumes:
      - ./logs:/app/logs

networks:
  shared-db-net:
    external:
      name: shared-db-net